name: phplint
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  phpstan_analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          tools: composer, composer-normalize, composer-require-checker, composer-unused, phplint, phpstan, phpunit
      - run: phpstan analyse .
  phplint_action_8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: overtrue/phplint@8.0
  phplint_action_9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: overtrue/phplint@9.0.4
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: cant,fo,inbetween,nam,numer
          skip: "*.css,*fr.html,*.js,*.json,*.lock,*.map,localization.php"
